// ActionTypes for an Entire Dictionary
export const CREATING_DICTIONARY = 'CREATING_DICTIONARY';
export const DELETING_DICTIONARY = 'DELETING_DICTIONARY';
export const EDITING_DICTIONARY = 'EDITING_DICTIONARY';